### PR TITLE
Fix edit filter bugs

### LINKED ISSUE #90: Fix Edit Bugs
1. Editing Name Error is never thrown.

Commands to replicate:
```
/pooch-add ; name : Pooch ; phone : 98883888 ; address : Pooch Street 32 ; email : impooch@gmail.com
/edit ; name : Pooch ; field : { name : Poochie }
```

Current Behaviour:
Error message "Failed to edit Pooch Contact - Field is empty! 🐾" is thrown.

Expected Behaviour:
Error message "Failed to edit Pooch Contact - Editing Pooch Contact names is not allowed 🐾" thrown.

2. Change the findByName to use non-filtered list instead of filtered list.

### LINKED ISSUE #117: Refactor edit command
Update error messages to be clear and more specific.

Add more unit test cases.

### PR DESCRIPTION
**Pull request by yleeyilin**
Fixes #117 
Fixes #90 

Handled error for extra prefix properly by return a clear description
of which the exact fields that are invalid. 

This helps improve usability as the users are able to better understand
how they can correct their command.

Additionally, I fixed the bugs regarding finding a person by name. Previously, 
our implementation used a filtered list. Thus, if a user searched for a person, 
then call either edit / delete / note, these functions will not allow if the person
to edit / delete / note is not within the filtered list.

### CODE REVIEW

**Review by jannaleong — APPROVED** [review]
LGTM! good validation checking.

File: src/main/java/seedu/address/logic/parser/EditSupplierCommandParser.java [hunk 1]
```diff
@@ -81,6 +98,57 @@ public EditSupplierCommand parse(String args) throws ParseException {
...
+        }
+        if (arePrefixesPresent(fieldArgMultimap, PREFIX_SKILL)) {
+            invalidFields.add("skill");
+        }
+        if (arePrefixesPresent(fieldArgMultimap, PREFIX_COMMISSION)) {
+            invalidFields.add("commission");
+        }
+        if (invalidFields.size() > 0) {
+            throw new ParseException(formatInvalidFieldString(invalidFields));
+        }
```
Comment (chiageng) [inline src/main/java/seedu/address/logic/parser/EditSupplierCommandParser.java:125]: Good catch of all error before throwing ParseException. This is a very detailed checking to help user to know which field should not exist in current edit

File: src/test/java/seedu/address/logic/commands/DeleteCommandTest.java [hunk 2]
```diff
@@ -47,28 +46,24 @@ public void execute_validNameFilteredList_success() {
...
-        }
+        assertCommandSuccess(deleteCommand, model, expectedMessage, expectedModel);
     }
 
     @Test
     public void execute_invalidNameFilteredList_throwsCommandException() {
         showPersonWithName(model, ALICE.getName());
 
-        Name invalidName = BENSON.getName();
+        Name invalidName = new Name("blbeo");
```
Comment (chiageng) [inline src/test/java/seedu/address/logic/commands/DeleteCommandTest.java:66]: It might be good idea to maintain a constant with INVALID_NAME so that it can be reused in most of the test cases

File: src/main/java/seedu/address/logic/parser/EditCommandParser.java [hunk 3]
```diff
@@ -41,13 +48,20 @@ public EditCommand parse(String args) throws ParseException {
         ArgumentMultimap argMultimap =
                 ArgumentTokenizer.tokenize(args, PREFIX_NAME, PREFIX_FIELD);
```
Comment (chiageng) [inline src/main/java/seedu/address/logic/parser/EditCommandParser.java:50]: What if we do 
Name name = ParserUtil.parseName(argMultimap.getValue(PREFIX_NAME).get());

Then we perform searchByName(name), to get the Person object. Then we check the exact Class of this Person.

By getting the Class of this Person, for eg : Staff, then we will return 
EditStaffCommandParser(args) to trigger edit staff action

Comment (yleeyilin) [reply src/main/java/seedu/address/logic/parser/EditCommandParser.java:50]: ill try it out thanks!

File: src/test/java/seedu/address/logic/commands/DeleteCommandTest.java (hunk 2 above)
Comment (yleeyilin) [reply src/test/java/seedu/address/logic/commands/DeleteCommandTest.java:66]: agreed!

**Review by chiageng — APPROVED** [review]
LGTM
